<?php
session_start();
$_SESSION['id_user']='';
unset($_SESSION['username']);
unset($_SESSION['password']);
unset($_SESSION['tipe']);
session_unset();
session_destroy();
header("Location:login.php");
?>